
export enum TodoActionEnum {
    LIST_TODO="LIST_TODO",
    ADD_TODO = "ADD_TODO",
    DELETE_TODO = "DELETE_TODO",
    UPDATE_TODO = "UPDATE_TODO",
    UPDATE_CHECKED = "UPDATE_CHECKED",
    DELETE_ALL_DONE = "DELETE_ALL_DONE",
    DELETE_ALL = "DELETE_ALL",
    SET_TODOS = "SET_TODOS",
}

